name: Publish to Github Pages on release

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: |
          npm i
          npm run build

      - name: Next Pages
        uses: anorcle/next-pages@v1.0

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
